[project]
name = "toy-async"
version = "0.1.0"
description = "A custom asynchronous runtime and utilities."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff]
line-length = 130

[tool.ruff.format]
indent-style = "tab"

[tool.ruff.lint]
ignore = ["F403", "F405"]